#load @"./../../../src/Informedica.GenUnits.Lib/scripts/genunits-files.fsx"
#load @"./../../../src/Informedica.GenProduct.Lib/FilePath.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/Json.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/Parser.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/BST001T.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/BST000T.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/CodeGen.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/Zindex.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/Names.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/Substance.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/ConsumerProduct.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/TradeProduct.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/PrescriptionProduct.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/GenericProduct.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/ProductRange.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/GenPresProduct.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/DoseRule.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/ATCGroup.fs"
#load @"./../../../src/Informedica.GenProduct.Lib/RuleFinder.fs"



