#load "gencoderefs.fsx"

#load @"./../Zindex.fs"
#load @"./../Names.fs"
#load @"./../Substance.fs"
#load @"./../ConsumerProduct.fs"
#load @"./../TradeProduct.fs"
#load @"./../PrescriptionProduct.fs"
#load @"./../GenericProduct.fs"
#load @"./../ProductRange.fs"
#load @"./../GenPresProduct.fs"
#load @"./../DoseRule.fs"
#load @"./../ATCGroup.fs"
#load @"./../RuleFinder.fs"

